# Site settings
title: Jahu im Blog!
email: mail@hehejo.de
description: In diesem Blog schreibe ich über Alles was mich interessiert, Kniffe und Tricks die ich gelernt habe, Zeug das ich teilenswert finde. Einfach so!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.hehejo.de" # the base hostname & protocol for your site

timezone: Europe/Berlin
encoding: utf-8

sass: 
    style: :compressed

# Build settings
future: false
exclude: ['Rakefile', 'Gemfile','Gemfile.lock', 'Procfile']
markdown: kramdown
# kramdown:
#    highlighter: rouge


defaults:
 -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      comments: true
      author: "Johannes"
 -
    scope:
      path: "" 
      type: "drafts" 
    values:
      layout: "post"


picture:
  source: "images/_fullsize"
  output: "generated"
  markup: "picture"
  presets:
     default:
          ppi: [1, 1.5, 2]
          attr:
            class: "default-pict"
          source_medium:
            media: "(max-width: 520px)"
            width: "220"
          source_default:
            width: "680"
     teaser:
             ppi: [1,1.5,2]
             attr:
                     class: "teaser-pict"
             source_default:
                     width: "680"
                     height: "156"
     # gallery:
     #      ppi: [1, 1.5]
     #      attr:
     #        class: "gallery-pict"
     #        itemprop: "image"
     #      source_medium:
     #        media: "(max-width: 520px)"
     #        width: "220"
     #      source_default:
     #        width: "680"

