# Site settings
title: Johannes sagt
email: mail@hehejo.de
description: > # this means to ignore newlines until "baseurl:"
  In diesem Blog schreibe ich über Dinge die mich interessieren, Dinge die ich gelernt habe, Dinge die ich teilenswert finde.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hehejo.de" # the base hostname & protocol for your site
twitter_username: hehejo
github_username:  hehejo

gems:
        - jekyll-minifier

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Johannes"
